16 add dialog with changelog
TBCounter/TBCounter-frontend pull request #17
Opened 2024-03-21 10:55 UTC by normalcore

2024-03-21 11:02 UTC, omega1996 requested changes

2024-03-21 11:02 UTC, omega1996 commented on src/layouts/LoginLayout.vue
> -
Зачем это?

2024-03-21 11:02 UTC, omega1996 commented on src/layouts/MainLayout.vue
> +onMounted(async () => {
Эту функцию нужно перенести ниже, под импорты, как и переменную changeLogs

2024-03-21 11:02 UTC, omega1996 commented on src/layouts/MainLayout.vue
> +  </div>
Нужно поправить отступы, настроить prettier и eslint

2024-03-21 11:26 UTC, omega1996 commented on src/layouts/MainLayout.vue
> +                  <div v-for="log in changeLogs" :key="log" class="q-py-xs">
Почему div, внутри которого q-item-label?
Разве не должно быть q-item?

2024-03-21 11:34 UTC, normalcore commented on src/layouts/MainLayout.vue
> +                  <div v-for="log in changeLogs" :key="log" class="q-py-xs">
q-item ломает формат скролла(

2024-03-21 11:37 UTC, omega1996 commented on src/layouts/MainLayout.vue
> +                  <div v-for="log in changeLogs" :key="log" class="q-py-xs">
Тогда q-item-label не нужен, либо то, либо другое, вообще лучше бы q-item остался

2024-03-21 11:39 UTC, normalcore commented on src/layouts/MainLayout.vue
> +                  <div v-for="log in changeLogs" :key="log" class="q-py-xs">
если я убираю q-item-label весь текст пропадает, остаются только даты

2024-03-21 11:45 UTC, omega1996 commented on src/layouts/MainLayout.vue
> +                  <div v-for="log in changeLogs" :key="log" class="q-py-xs">
https://quasar.dev/vue-components/dialog/#example--scrollable-dialogs

2024-03-21 12:18 UTC, omega1996 commented on src/layouts/MainLayout.vue
> +              <q-item v-for="log in changeLogs" :key="log">
q-item Всегда вложен в q-list, судя по документации

https://quasar.dev/vue-components/list-and-list-items/

2024-03-21 12:26 UTC, normalcore commented on src/layouts/MainLayout.vue
> +              <q-item v-for="log in changeLogs" :key="log">
я не понял о чем ты

2024-03-22 03:42 UTC, omega1996 approved these changes

2024-03-22 03:43 UTC, merged